### ISSUE TITLE
Chain with nuclei doesn't work

### ISSUE THREAD

**Issue by whitehat92** [dwisiswant0/go-dork#12]
when running the command set in the example to chain with other tools like nuclei, for jira, after I debug this is what showed up
[WRN] [microstrategy-detect] Could not execute request for <url>: parse "\x1b[32m<url>/\x1b[0m": net/url: invalid control character in URL
This doesn't happen if I save the urls into a file and cat those out; nuclei will correctly identify the technologies.
So.. is there anyway you could fix the pipe option? I believe it's because your logo still shows up in silent mode.
Thank you so much. Let me know if you need more examples

**Comment by dwisiswant0** [comment]
Thanks for spotting this. It happens because the color is printable to stdout, I'll make it disabled by default.

**Comment by whitehat92** [comment]
Thank you very much. If you could update the release file, that would be great!
