### ISSUE TITLE
Problem installing with build

### ISSUE THREAD

**Issue by whitehat92** [dwisiswant0/go-dork#13]
When trying to build or using get, always this error of some package that is not in GOROOT

golang_org/x/net/lex/httplex: package golang_org/x/net/lex/httplex is not in GOROOT (/usr/lib/go-1.7/src/golang_org/x/net/lex/httplex)

I'm not sure if the error is on my side.
If possible, please update the release file, in order to reflect https://github.com/dwisiswant0/go-dork/issues/12

Thank you very much and great job, once again :)

**Comment by dwisiswant0** [comment]
Hi, you just only need to run `go build .` to build from source, and we didn't realize that our binary releaser is broken. But, now it's live on https://github.com/dwisiswant0/go-dork/releases/tag/v1.0.2. Thanks!
