### ISSUE TITLE
Why doesn't kali work on linux?

### ISSUE THREAD

**Issue by MahmutNadim** [dwisiswant0/go-dork#16]
I downloaded the file.
GO111MODULE=on go install dw1.io/go-dork@latest
I got the controls.
from the terminal
  When you run go-dork -h
go-dork: command not found

Gives a fault. Please, how do we install? Can you give detailed information about how to work?

**Comment by avdebor** [comment]
same issue, cant run it even from git-cloned repository lol

**Comment by Username2022a** [comment]
Same here. This tool dosen't seem to work in Kali Linux.

**Comment by unfairDude** [comment]
u noobs can even set gopath properly

**Comment by bcoles** [comment]
> same issue, cant run it even from git-cloned repository lol

```
git clone https://github.com/dwisiswant0/go-dork
cd go-dork
go build
./go-dork
```
