### ISSUE TITLE
input from dorks in stdin is all added into a single query

### ISSUE THREAD

**Issue by whitehat92** [dwisiswant0/go-dork#6]
if you have in your dorks file like this:
"Index of/"
inurl:example.com

the script will read and transform in a query as ["Index of" inurl:example.com]. All the dorks are added to the query in a single line, which decreases the odds of getting any desirable result.
As a workaround, what I'm doing is basically cat dorks | xargs -I {} go-dork -q "{}" -e <search engine>. Works just fine
Because of this, it would be nice to run from stdin and for each line on dorks file adding a new line in the query. So, instead of interpreting each line as new data to be added to a single query, just run it for each line and run as a single query for each line:
query "index of/" --> search
query "inurl:example.com --> search

Wonderful tool, never the less. Very good job!

**Comment by dwisiswant0** [comment]
No, that didn't happen. It's just a display, actually it will be executed correctly. Try to debug it with Burp Suite or another proxy to monitor your requests.
![Screenshot_2021-04-08_13-30-36](https://user-images.githubusercontent.com/25837540/113978991-e2925f00-986e-11eb-83bf-96bada222ad9.png)

**Comment by whitehat92** [comment]
I just tested and you're absolutely right, I was running it and just checking how the query was being made. Very sorry to raise this issue. Thank you so much for your fast reply. Once again, excellent tool
